remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Karanjot Singh Saggu
description: Ex-Data Scientist. Experience with Machine Learning, Data Science, and Data Analytics
