remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Karanjot's homepage
description: Data Scientist by Professor. Experience with Machine Learning, Data Science and Data Analytics
